// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Motivation.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Motivation.Infrastructure.Migrations
{
    [DbContext(typeof(MotivationDbContext))]
    [Migration("20260610062803_UpdateKpiHierarchy")]
    partial class UpdateKpiHierarchy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Motivation.Domain.Entities.Deduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeductionValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("EmployeePositionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EmployeePositionId");

                    b.ToTable("deductions", (string)null);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FullName");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.EmployeePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PositionId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("employee_positions", (string)null);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.ExtraPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeePositionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ExtraPartValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EmployeePositionId");

                    b.ToTable("extra_parts", (string)null);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.KpiFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KpiFilterType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("KpiId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KpiId");

                    b.HasIndex("Title");

                    b.ToTable("kpi_filters", (string)null);

                    b.HasDiscriminator<int>("KpiFilterType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Motivation.Domain.Entities.Kpis.Kpi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("KpiType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MeasurementUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("Title");

                    b.ToTable("kpis", (string)null);

                    b.HasDiscriminator<int>("KpiType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Motivation.Domain.Entities.MeasurementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("measurement_unit", (string)null);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkWeekType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.PositionKpi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Achievement")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BonusAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fact")
                        .HasColumnType("numeric");

                    b.Property<Guid>("KpiId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Target")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("KpiId");

                    b.HasIndex("PositionId");

                    b.ToTable("position_kpis", (string)null);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.StandardHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("StandardHoursValue")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkWeekType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("standard_hours", (string)null);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.KpiFilterCompany", b =>
                {
                    b.HasBaseType("Motivation.Domain.Entities.KpiFilter");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.KpiFilterCustomer", b =>
                {
                    b.HasBaseType("Motivation.Domain.Entities.KpiFilter");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.KpiFilterProduct", b =>
                {
                    b.HasBaseType("Motivation.Domain.Entities.KpiFilter");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.Kpis.ComplexityKpi", b =>
                {
                    b.HasBaseType("Motivation.Domain.Entities.Kpis.Kpi");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.Kpis.SalesKpi", b =>
                {
                    b.HasBaseType("Motivation.Domain.Entities.Kpis.Kpi");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Motivation.Domain.Entities.Deduction", b =>
                {
                    b.HasOne("Motivation.Domain.Entities.EmployeePosition", "EmployeePosition")
                        .WithMany("DeductionHistory")
                        .HasForeignKey("EmployeePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeePosition");
                });

            modelBuilder.Entity("Motivation.Domain.Entities.EmployeePosition", b =>
                {
                    b.HasOne("Motivation.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeePositions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Domain.Entities.Position", "Position")
                        .WithMany("EmployeePositions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Motivation.Domain.Entities.ExtraPart", b =>
                {
                    b.HasOne("Motivation.Domain.Entities.EmployeePosition", "EmployeePosition")
                        .WithMany("ExtraPartHistory")
                        .HasForeignKey("EmployeePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeePosition");
                });

            modelBuilder.Entity("Motivation.Domain.Entities.KpiFilter", b =>
                {
                    b.HasOne("Motivation.Domain.Entities.Kpis.Kpi", null)
                        .WithMany("Filters")
                        .HasForeignKey("KpiId");
                });

            modelBuilder.Entity("Motivation.Domain.Entities.Kpis.Kpi", b =>
                {
                    b.HasOne("Motivation.Domain.Entities.MeasurementUnit", "MeasurementUnit")
                        .WithMany("Kpis")
                        .HasForeignKey("MeasurementUnitId");

                    b.Navigation("MeasurementUnit");
                });

            modelBuilder.Entity("Motivation.Domain.Entities.Position", b =>
                {
                    b.OwnsOne("Motivation.Domain.Entities.MotivationPart", "MotivationPart", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("MotivationPartValue")
                                .HasColumnType("numeric");

                            b1.Property<bool>("RecalculateToHours")
                                .HasColumnType("boolean");

                            b1.HasKey("PositionId");

                            b1.ToTable("positions");

                            b1
                                .ToJson("MotivationPart")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.Navigation("MotivationPart")
                        .IsRequired();
                });

            modelBuilder.Entity("Motivation.Domain.Entities.PositionKpi", b =>
                {
                    b.HasOne("Motivation.Domain.Entities.Kpis.Kpi", "Kpi")
                        .WithMany()
                        .HasForeignKey("KpiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Domain.Entities.Position", "Position")
                        .WithMany("PositionKpiHistory")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kpi");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Motivation.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmployeePositions");
                });

            modelBuilder.Entity("Motivation.Domain.Entities.EmployeePosition", b =>
                {
                    b.Navigation("DeductionHistory");

                    b.Navigation("ExtraPartHistory");
                });

            modelBuilder.Entity("Motivation.Domain.Entities.Kpis.Kpi", b =>
                {
                    b.Navigation("Filters");
                });

            modelBuilder.Entity("Motivation.Domain.Entities.MeasurementUnit", b =>
                {
                    b.Navigation("Kpis");
                });

            modelBuilder.Entity("Motivation.Domain.Entities.Position", b =>
                {
                    b.Navigation("EmployeePositions");

                    b.Navigation("PositionKpiHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
